name: Build library (yjs)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library (Vite lib mode)
        run: pnpm vite build --config vite.lib.config.ts

      - name: Upload library artifact
        uses: actions/upload-artifact@v4
        with:
          name: y-mxgraph-lib
          path: dist
